export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';
export const START_FETCH_SEARCH_DATA = 'START_FETCH_SEARCH_DATA';
export const FINISH_SEARCH = 'FINISH_SEARCH';