export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';
export const START_FETCH_SEARCH_DATA = 'START_FETCH_SEARCH_DATA';
export const FINISH_SEARCH = 'FINISH_SEARCH';
export const SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST';
export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST';
export const UPDATE_CHAT_USER = 'UPDATE_CHAT_USER';